//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostCodeSerialMonitor.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("VS Code RESX Editor", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PostCodeSerialMonitor.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   In Models/JsonConverters.cs file
        /// </summary>
        public static string ExpectedStringToken {
            get {
                return ResourceManager.GetString("ExpectedStringToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Models/JsonConverters.cs file
        /// </summary>
        public static string FailedReadingString {
            get {
                return ResourceManager.GetString("FailedReadingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Models/JsonConverters.cs file
        /// </summary>
        public static string InvalidBase64String {
            get {
                return ResourceManager.GetString("InvalidBase64String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/ConfigurationService.cs
        /// </summary>
        public static string ConfigurationSaved {
            get {
                return ResourceManager.GetString("ConfigurationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/ConfigurationService.cs
        /// </summary>
        public static string FailedSaveConfiguration {
            get {
                return ResourceManager.GetString("FailedSaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/ConfigurationService.cs
        /// </summary>
        public static string ConfigurationUpdated {
            get {
                return ResourceManager.GetString("ConfigurationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/ConfigurationService.cs
        /// </summary>
        public static string FailedUpdateConfiguration {
            get {
                return ResourceManager.GetString("FailedUpdateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/MetaDefinitionService.cs
        /// </summary>
        public static string MetaFileNotExist {
            get {
                return ResourceManager.GetString("MetaFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/MetaDefinitionService.cs
        /// </summary>
        public static string UnexpectedMetaType {
            get {
                return ResourceManager.GetString("UnexpectedMetaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/MetaUpdateService.cs
        /// </summary>
        public static string MetaContent {
            get {
                return ResourceManager.GetString("MetaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/MetaUpdateService.cs
        /// </summary>
        public static string FailedDownloadMetaEntry {
            get {
                return ResourceManager.GetString("FailedDownloadMetaEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/MetaUpdateService.cs
        /// </summary>
        public static string FailedDeserializingMetaDefinition {
            get {
                return ResourceManager.GetString("FailedDeserializingMetaDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/MetaUpdateService.cs
        /// </summary>
        public static string FailedDownloadMetaDefinition {
            get {
                return ResourceManager.GetString("FailedDownloadMetaDefinition", resourceCulture);
            }
        }

        /// <summary>
        ///   In Services/MetaUpdateService.cs
        /// </summary>
        public static string FailedDeserializingReleaseDefinition {
            get {
                return ResourceManager.GetString("FailedDeserializingReleaseDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/MetaUpdateService.cs
        /// </summary>
        public static string FailedDownloadReleaseDefinition {
            get {
                return ResourceManager.GetString("FailedDownloadReleaseDefinition", resourceCulture);
            }
        }

        /// <summary>
        ///   In Services/SerialLineDecoder.cs
        /// </summary>
        public static string DecoderIgnoringLine {
            get {
                return ResourceManager.GetString("DecoderIgnoringLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/SerialLineDecoder.cs
        /// </summary>
        public static string UemOsError {
            get {
                return ResourceManager.GetString("UemOsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/SerialService.cs
        /// </summary>
        public static string FailedEnterRepl {
            get {
                return ResourceManager.GetString("FailedEnterRepl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/SerialService.cs
        /// </summary>
        public static string FailedFwVersion {
            get {
                return ResourceManager.GetString("FailedFwVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/SerialService.cs
        /// </summary>
        public static string FailedParseConfig {
            get {
                return ResourceManager.GetString("FailedParseConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/SerialService.cs
        /// </summary>
        public static string FailedGetVersion {
            get {
                return ResourceManager.GetString("FailedGetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Services/SerialService.cs
        /// </summary>
        public static string FailedGetState {
            get {
                return ResourceManager.GetString("FailedGetState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string ScanButtonText {
            get {
                return ResourceManager.GetString("ScanButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string NewMetadataAvailable {
            get {
                return ResourceManager.GetString("NewMetadataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string NewMetadataAvailableInformation {
            get {
                return ResourceManager.GetString("NewMetadataAvailableInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string FailedUpdateMetadata {
            get {
                return ResourceManager.GetString("FailedUpdateMetadata", resourceCulture);
            }
        }

        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string NewAppReleaseAvailable {
            get {
                return ResourceManager.GetString("NewAppReleaseAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string NewFirmwareReleaseAvailable {
            get {
                return ResourceManager.GetString("NewFirmwareReleaseAvailable", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string FailedUpdateMetadataMessageBoxError {
            get {
                return ResourceManager.GetString("FailedUpdateMetadataMessageBoxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string FailedLoadLocalMetadata {
            get {
                return ResourceManager.GetString("FailedLoadLocalMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string FailedLoadLocalMetadataMessageBoxWarning {
            get {
                return ResourceManager.GetString("FailedLoadLocalMetadataMessageBoxWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string FailedLoadMetadata {
            get {
                return ResourceManager.GetString("FailedLoadMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string FailedLoadLocalMetadataMessageBoxError {
            get {
                return ResourceManager.GetString("FailedLoadLocalMetadataMessageBoxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string SaveLogFiles {
            get {
                return ResourceManager.GetString("SaveLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string LogFiles {
            get {
                return ResourceManager.GetString("LogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string ErrorSavingLogFile {
            get {
                return ResourceManager.GetString("ErrorSavingLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string ErrorSavingLogFileMessageBoxError {
            get {
                return ResourceManager.GetString("ErrorSavingLogFileMessageBoxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string ErrorConection {
            get {
                return ResourceManager.GetString("ErrorConection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string ErrorConectionMessageBoxError {
            get {
                return ResourceManager.GetString("ErrorConectionMessageBoxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string FailedGetMainWindow {
            get {
                return ResourceManager.GetString("FailedGetMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In ViewModels/MainWindowViewModel.cs
        /// </summary>
        public static string FailedGetApplicationLifetime {
            get {
                return ResourceManager.GetString("FailedGetApplicationLifetime", resourceCulture);
            }
        }

        /// <summary>
        ///   In Views/ConfigurationDialog.axaml
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }

        /// <summary>
        ///   In Views/ConfigurationDialog.axaml
        /// </summary>
        public static string LanguageSettings
        {
            get
            {
                return ResourceManager.GetString("LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/ConfigurationDialog.axaml
        /// </summary>
        public static string UpdateSettings {
            get {
                return ResourceManager.GetString("UpdateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/ConfigurationDialog.axaml
        /// </summary>
        public static string CheckApplicationUpdates {
            get {
                return ResourceManager.GetString("CheckApplicationUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/ConfigurationDialog.axaml
        /// </summary>
        public static string ApplicationUpdateUrl {
            get {
                return ResourceManager.GetString("ApplicationUpdateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml
        /// </summary>
        public static string CheckCodeUpdates {
            get {
                return ResourceManager.GetString("CheckCodeUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml
        /// </summary>
        public static string CodeMetaUrl {
            get {
                return ResourceManager.GetString("CodeMetaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml
        /// </summary>
        public static string CheckFirmwareUpdates {
            get {
                return ResourceManager.GetString("CheckFirmwareUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml
        /// </summary>
        public static string FirmwareUpdateUrl {
            get {
                return ResourceManager.GetString("FirmwareUpdateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml
        /// </summary>
        public static string XboxPostCodeSerialMonitor {
            get {
                return ResourceManager.GetString("XboxPostCodeSerialMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml
        /// </summary>
        public static string RefreshPorts {
            get {
                return ResourceManager.GetString("RefreshPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml
        /// </summary>
        public static string SaveLog {
            get {
                return ResourceManager.GetString("SaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml
        /// </summary>
        public static string VisitXboxResearch {
            get {
                return ResourceManager.GetString("VisitXboxResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml.cs
        /// </summary>
        public static string PicoFirmware {
            get {
                return ResourceManager.GetString("PicoFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml.cs
        /// </summary>
        public static string MetadataUpdate {
            get {
                return ResourceManager.GetString("MetadataUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Views/MainWindow.axaml.cs
        /// </summary>
        public static string FailedOpenUrl {
            get {
                return ResourceManager.GetString("FailedOpenUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   In ViewModels/ConfigurationDialogViewModel.cs
        /// </summary>
        public static string RestartRequired
        {
            get
            {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   In ViewModels/ConfigurationDialogViewModel.cs
        /// </summary>
        public static string LanguageChangedPleaseRestart
        {
            get
            {
                return ResourceManager.GetString("LanguageChangedPleaseRestart", resourceCulture);
            }
        }
    }
}
